name: Build PyTorch 2.3 for Jetson

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push PyTorch 2.3 Image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/pytorch
          file: ./packages/pytorch/Dockerfile
          platforms: linux/arm64
          push: true
          tags: RuybeAI/pytorch:2.3-all
