name: Build PyTorch 2.3 for Jetson

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to NVIDIA NGC
        run: |
          echo "${{ secrets.NGC_API_KEY }}" \
            | docker login nvcr.io \
                --username '$oauthtoken' \
                --password-stdin

      - name: Build & push on JetPack base
        uses: docker/build-push-action@v4
        with:
          context: ./packages/pytorch
          file:    ./packages/pytorch/Dockerfile
          platforms: linux/arm64
          build-args: |
            BASE_IMAGE=nvcr.io/nvidia/l4t-jetpack:r36.4.0
            TORCH_CUDA_ARCH_LIST=8.7
          push: true
          tags: RuybeAI/pytorch:2.3-jp6.2-all

      - name: Build & push on L4T-PyTorch base
        uses: docker/build-push-action@v4
        with:
          context: ./packages/pytorch
          file:    ./packages/pytorch/Dockerfile
          platforms: linux/arm64
          build-args: |
            BASE_IMAGE=nvcr.io/nvidia/l4t-pytorch:r36.4.3-pytorch-py3
            TORCH_CUDA_ARCH_LIST=8.7
          push: true
          tags: RuybeAI/pytorch:2.3-all
